name: Auto Minify

on: ["push"]

jobs:
  auto-minify:
    name: Auto-Minify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1.1
        with:
          maxdepth: 3
          output: 'minified'

      - name: Auto committing minified files to 'minified' directory
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: 'minified'
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}  
