name: HTML5 Validator
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.0.0
        with:
          root: source/
          log_level: INFO
          css: true
      - uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.log
