name: jsdoc
on: [push]
# push:
 #  branches:
   #  - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: codevise/documentation-js-action@v1
      with:
        input: ./src
        output: ./docs

    # For example:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.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 }}
        PUBLISH_BRANCH: main
        PUBLISH_DIR: ./docs
