name: JSDoc
on: ["push"]

#on:
 # push:
   # branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          repository: cse110-fa21-group12/cse110-fa21-group12
          path: docs       
        
      - name: Build
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./source
          recurse: true
          output_dir: docs
          front_page: README.md
        