name: JSDoc
on: ["push"]

#on:
 # push:
   # branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          repository: cse110-fa21-group12/cse110-fa21-group12
          path: docs       
        
      - name: Build
        uses: codevise/documentation-js-action@v1
        with:
          input: ./source
          output: docs

name: jsdoc
on:
 push:
   branches:
     - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: codevise/documentation-js-action@v1
      with:
        input: ./src
        output: ./docs

    # For example:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.DOCS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
        