name: jsdoc
on: [push]
# push:
 #  branches:
   #  - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: codevise/documentation-js-action@v1
      with:
        input:  ./
        output: ./docs

    # For example:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.DOCS_TOKEN }}
        PUBLISH_BRANCH: r_main
        PUBLISH_DIR: ./docs