

name: jsdoc
on:
 push:
   branches:
     - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: codevise/documentation-js-action@v1
      with:
        input: source/
        output: source/

  
