name: jsdoc
on: [push]
# push:
 #  branches:
   #  - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        output_dir: ./out
        config_file: config.js
        front_page: README.md

    # For example:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.DOCS_TOKEN }}
        PUBLISH_BRANCH: r_main
        PUBLISH_DIR: ./docs