name: JSDoc
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          repository: cse110-fa21-group12.github.io/cse110-fa21-group12
          path: docs
          token: ${{ secrets.DOCS_TOKEN }}
          
      - name: npm version
        run: npm -v
        
      - name: Build
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./source/
          recurse: true
          output_dir: docs/docs
          front_page: docs/README.md
      - name: Commit and push documentation
        run: |
          cd docs
          git add -A
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Added documentation for app."
          git push https://$USERNAME:$REPO_KEY@github.com/cse110-fa21-group12/cse110-fa21-group12.git main
          
        env:
          REPO_KEY: ${{ secrets.DOCS_TOKEN }}
          USERNAME: github-actions[bot]