name: JSDoc
on: [push]

jobs:
  docs:
    name: docs-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Run automatic doc generation
        uses: andstor/jsdoc-action@v1
        with:
         source_dir: ./source
         recurse: true
         output_dir: ./docs
         template: minami

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.DOCS_TOKEN }}
          PUBLISH_DIR: ./docs
          PUBLISH_BRANCH: github_workflows
